version: '3.7'
services:
  server:
    image: shlinkio/shlink
    depends_on:
      - db
    networks:
      - lan
      - wan
    environment:
      SHORT_DOMAIN_HOST: "w.max.local"
      SHORT_DOMAIN_SCHEMA: "https"
      NOT_FOUND_REDIRECT_TO: "https://www.canel.ch"
      DB_DRIVER: "postgres"
      DB_HOST: "db"
      DB_NAME: "shlink"
      DB_USER: "user"
      DB_PASSWORD: "dbpass"
      VALIDATE_URLS: "false"
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:w.max.local'
      - 'traefik.port=8080'
      - 'traefik.docker.network=wan'

  db:
    image: postgres:11
    restart: always
    networks:
      - lan
    ports:
      - 5432:5432  
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: user
      POSTGRES_DB: shlink
    volumes:
      - db:/var/lib/postgresql/data


  webui:
    image: shlinkio/shlink-web-client
    depends_on:
      - server
    networks:
      - lan
      - wan
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:shlink.max.local'
      - 'traefik.port=80'
      - 'traefik.docker.network=wan'

networks:
  lan: 
  wan:
    name: traefik_wan
    external: True

volumes:
  db:
